package com.example.myday.ui.theme

import androidx.compose.ui.graphics.Color

// Kawaii Day (Pink)
val PinkPrimary = Color(0xFFFFB6C1)
val PinkOnPrimary = Color(0xFFFFFFFF)
val PinkPrimaryContainer = Color(0xFFFFD1DC)
val PinkOnPrimaryContainer = Color(0xFF3B0017)
val PinkSecondary = Color(0xFFFF91A4)
val PinkOnSecondary = Color(0xFFFFFFFF)
val PinkSecondaryContainer = Color(0xFFFFD8E4)
val PinkOnSecondaryContainer = Color(0xFF3D0014)
val PinkTertiary = Color(0xFFF8BBD0)
val PinkOnTertiary = Color(0xFF3E001D)
val PinkTertiaryContainer = Color(0xFFFFD8E6)
val PinkOnTertiaryContainer = Color(0xFF31101D)
val PinkBackground = Color(0xFFFFF5F7)
val PinkOnBackground = Color(0xFF25191B)
val PinkSurface = Color(0xFFFFF5F7)
val PinkOnSurface = Color(0xFF25191B)

// Kawaii Night (Purple)
val PurplePrimary = Color(0xFFD8BFD8)
val PurpleOnPrimary = Color(0xFF3C2847)
val PurplePrimaryContainer = Color(0xFF533F5F)
val PurpleOnPrimaryContainer = Color(0xFFF6D9FF)
val PurpleSecondary = Color(0xFFE6E6FA)
val PurpleOnSecondary = Color(0xFF1B192B)
val PurpleSecondaryContainer = Color(0xFF312E41)
val PurpleOnSecondaryContainer = Color(0xFFE7DFF8)
val PurpleTertiary = Color(0xFFB19CD9)
val PurpleOnTertiary = Color(0xFF271B3E)
val PurpleTertiaryContainer = Color(0xFF3E3156)
val PurpleOnTertiaryContainer = Color(0xFFEFDBFF)
val PurpleBackground = Color(0xFF1C1B1F)
val PurpleOnBackground = Color(0xFFE6E1E5)
val PurpleSurface = Color(0xFF1C1B1F)
val PurpleOnSurface = Color(0xFFE6E1E5)
